// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StayNGo.Infrastructure.Persistence;

#nullable disable

namespace StayNGo.Infrastructure.Migrations
{
    [DbContext(typeof(StayNGoDbContext))]
    [Migration("20260625073637_AddIdempotencyKeyToBooking")]
    partial class AddIdempotencyKeyToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StayNGo.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuestUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_user_id");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "StayNGo.Domain.Entities.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("total_price_amount_cents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("GuestUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_guest_user_id_idempotency_key");

                    b.HasIndex("ListingId", "CheckIn", "CheckOut")
                        .HasDatabaseName("ix_bookings_listing_id_check_in_check_out");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("main_image_url");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "StayNGo.Domain.Entities.Listing.Price#Money", b1 =>
                        {
                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("price_amount_cents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_listings_owner_user_id");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ClerkId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_clerk_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.Booking", b =>
                {
                    b.HasOne("StayNGo.Domain.Entities.User", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_guest_user_id");

                    b.HasOne("StayNGo.Domain.Entities.Listing", "Listing")
                        .WithMany("Bookings")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_listings_listing_id");

                    b.Navigation("Guest");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.Listing", b =>
                {
                    b.HasOne("StayNGo.Domain.Entities.User", "Owner")
                        .WithMany("Listings")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_owner_user_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.Listing", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("StayNGo.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
